### ISSUE TITLE
sysctl-related build failures with glibc 2.31+

### ISSUE THREAD

**Issue by agbrooks** [flightaware/tclbsd#11]
Linux 5.5 removed the `sysctl` syscall, prompting [`glibc` to remove `sys/sysctl.h`](https://sourceware.org/pipermail/glibc-cvs/2020q2/069366.html), which [`tclbsd` needs in order to compile](https://github.com/flightaware/tclbsd/blob/master/generic/sysctl.c#L22).

I believe only `glibc` 2.31 and later are affected. (I've seen this problem with the `nixpkgs-20.09` release of `glibc` (2.31), and the [changelog for 2.30](https://sourceware.org/legacy-ml/libc-alpha/2019-08/msg00029.html) indicates that it was still included, but was deprecated.)

**Comment by resuna** [comment]
Try building the Issue11 branch and see if that fixes it.

**Comment by agbrooks** [comment]
The Issue11 branch seems to work. Thank you!

**Comment by resuna** [comment]
Can you try again, I added a test for the sysctl.h file explicitly in configure.in, so you'll need to autoreconf and configure again.

**Comment by agbrooks** [comment]
Sure. It still works with your latest commit.
